accounts/urls.py
from django.conf.urls import url
from .import views

app_name='accounts'

urlpatterns = [
    url('signup/', views.signup_view, name="signup"),
    url('login/', views.login_view, name="login"),
    url('logout/', views.logout_vew, name="logout"),
]

articles/tasks/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about',views.about),
    path('',views.homepage),
    path('naqib', views.naqib),
    path('articles/', include('articles.urls')),
    path('one', include('articles.urls')),

]

urlpatterns += staticfiles_urlpatterns()

articles/urls.py
from django.urls import path
from .import views
from django.conf.urls import include, url

app_name = 'articles'

urlpatterns = [

    path('',views.article_list, name="list"),
    path('one', views.article_one, name = "one"),
    path('create', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail"),


]

tasks/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',article_views.article_list, name="home"),
    path('articles/', include('articles.urls')),
    path('one', include('articles.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE, default=None)
    # add in thumbnail later
    # add in author later

#everytime we add new
# python manage.py makemigrations
# python manage.py migrate

def __str__(self):
    return self.title

def snippet(self):
    return self.body[:50]+'helo buddy'

articles/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_vew(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/tasks/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, "homepage.html")

def about(request):
    # return HttpResponse('about')
    return render(request, "about.html")

def naqib(request):
     return HttpResponse('hidayat is an idiot')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms
# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles': articles})

def article_one(request):
    return  render(request, 'articles/article_one.html')
def article_detail(request, slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article todb
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form':form})

tasks/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, "homepage.html")

def about(request):
    # return HttpResponse('about')
    return render(request, "about.html")

def naqib(request):
     return HttpResponse('hidayat is an idiot')

accounts/templates/accounts/login.html
{% extends 'base_layouts.html' %}


{% block content %}
  <h1>Log in</h1>
  <form class="site-form" action="/accounts/login/" method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
      {% endif %}
    <input type="submit" value="Login">
  </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layouts.html' %}


{% block content %}
  <h1>Signup</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layouts.html' %}

{% block content %}
<div class="create-article">
  <h2>Create a new Article.</h2>
  <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create">
  </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layouts.html' %}

{% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{article.thumb.url}}"/>
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layouts.html' %}
{% block content %}

    <h1>Article List</h1>
    <div class="articles">
      {% for article in articles %}
        <div class="article">
          <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
          <p>{{article.snippet}}</p>
          <p>{{article.date}}</p>
          <p class="author">added by {{article.author.username}}</p>
        </div>
      {% endfor %}
    </div>
{% endblock %}

articles/templates/articles/article_one.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Article One</title>
  </head>
  <body>
    <h1>Your now loged out.</h1>
  </body>
</html>

templates/base_layouts.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Articles</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  </head>
  <body>
    <header class="wrapper"></header>
    <div class="wrapper">
      <h3> <a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" <="" a="" style="width: 70px;"></a></h3>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
          </li>
          <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
          {% else %}
            <li class="but"><a href="{% url 'accounts:login' %}">Login</a></li>
            <li class="but"><a href="{% url 'accounts:signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
      {% block content %}
      {% endblock %}
</div>
  </body>
</html>